# Generated by Django 4.0.6 on 2022-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Intern'), ('F', 'Full-time'), ('P', 'Part-time')], max_length=128)),
                ('salary', models.FloatField()),
                ('duration', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
            ],
        ),
    ]
