# Generated by Django 4.0.6 on 2022-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
