# Generated by Django 4.0.6 on 2022-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
