# Generated by Django 4.0.6 on 2022-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_image_trending_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reqs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
